"""Terraform HCL generator for the ``terraform.generate`` capability (U6).

Produces a module putting N containers (ECS Fargate services) behind an AWS
Application Load Balancer: ``aws_lb``, ``aws_lb_target_group``,
``aws_lb_listener``, and one ``aws_ecs_task_definition`` +
``aws_ecs_service`` pair per container.

Also provides :func:`validate_own_output`, the agent's own syntactic
self-check (balanced braces outside strings/comments + at least one
``resource`` block). This deliberately mirrors what an independent verifier
would check, but is implemented here from the spec alone — no imports from
the reference services.
"""

import re

SUPPORTED_LOAD_BALANCERS = ("alb",)

_RESOURCE_BLOCK_RE = re.compile(
    r'(^|\n)\s*resource\s+"[^"\n]+"\s+"[^"\n]+"\s*\{'
)

_HEADER = '''\
# Generated by the AgentTrust demo provider agent.
# {containers} container service(s) behind an AWS Application Load Balancer.

resource "aws_lb" "app" {{
  name               = "agenttrust-demo-alb"
  internal           = false
  load_balancer_type = "application"
  subnets            = var.public_subnet_ids
  security_groups    = [var.alb_security_group_id]
}}

resource "aws_lb_target_group" "app" {{
  name        = "agenttrust-demo-tg"
  port        = 80
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {{
    path    = "/healthz"
    matcher = "200"
  }}
}}

resource "aws_lb_listener" "http" {{
  load_balancer_arn = aws_lb.app.arn
  port              = 80
  protocol          = "HTTP"

  default_action {{
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }}
}}
'''

_CONTAINER_BLOCK = '''
resource "aws_ecs_task_definition" "app_{index}" {{
  family                   = "agenttrust-demo-app-{index}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"
  container_definitions = jsonencode([
    {{
      name      = "app-{index}"
      image     = var.container_image
      essential = true
      portMappings = [
        {{
          containerPort = 80
          protocol      = "tcp"
        }}
      ]
    }}
  ])
}}

resource "aws_ecs_service" "app_{index}" {{
  name            = "agenttrust-demo-app-{index}"
  cluster         = var.ecs_cluster_arn
  task_definition = aws_ecs_task_definition.app_{index}.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {{
    subnets         = var.private_subnet_ids
    security_groups = [var.service_security_group_id]
  }}

  load_balancer {{
    target_group_arn = aws_lb_target_group.app.arn
    container_name   = "app-{index}"
    container_port   = 80
  }}
}}
'''


def generate_terraform(containers, load_balancer):
    # type: (int, str) -> str
    """Generate an HCL module: ``containers`` services behind an ALB.

    Raises :class:`ValueError` on invalid input — the agent never emits a
    broken artifact for bad input; it fails the request instead.
    """
    if isinstance(containers, bool) or not isinstance(containers, int):
        raise ValueError("containers must be an integer")
    if containers < 1:
        raise ValueError("containers must be >= 1")
    if load_balancer not in SUPPORTED_LOAD_BALANCERS:
        raise ValueError(
            "unsupported load_balancer %r (supported: %s)"
            % (load_balancer, ", ".join(SUPPORTED_LOAD_BALANCERS))
        )
    parts = [_HEADER.format(containers=containers)]
    for index in range(1, containers + 1):
        parts.append(_CONTAINER_BLOCK.format(index=index))
    return "".join(parts)


def validate_own_output(text):
    # type: (object) -> bool
    """Syntactic self-check: balanced braces + at least one resource block.

    String-aware (honors backslash escapes) and skips ``#`` line comments,
    so braces inside strings or comments do not skew the balance.
    """
    if not isinstance(text, str) or not text.strip():
        return False
    depth = 0
    in_string = False
    escaped = False
    in_comment = False
    for ch in text:
        if in_comment:
            if ch == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            elif ch == "\n":
                return False  # unterminated string literal
            continue
        if ch == '"':
            in_string = True
        elif ch == "#":
            in_comment = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                return False
    if in_string or depth != 0:
        return False
    return bool(_RESOURCE_BLOCK_RE.search(text))
