"""Postgres-backed storage for principals, keys, organizations and teams
(unit U2, ``identity`` schema -- ``migrations/0001_identity.sql``).

This is the storage swap ``registry/agent_index.py`` (see its
``register_agent``/``find_by_capability``) and ``registry/user_index.py``
(``create_user``/``get_reputation_records``) eventually rewire onto in U5 --
method names below mirror that existing vocabulary (``register_*``,
``get_*``, ``*_exists``, ``update_last_active``) on purpose, so that rewire
reads as a natural swap of the storage underneath, not a redesign of the
calling code.

``identity.principals`` unifies what ``AgentIndex`` and ``UserIndex`` each
kept as a separate near-duplicate table: every principal (user, agent,
verifier or service) is one row here, distinguished by ``principal_type``.
``principal_id`` itself is never generated by this module -- it is the
caller's ed25519-derived identity string (RFC-0001), supplied already
formed, exactly as every other store in this codebase already treats it.

Every *new* surrogate key this module introduces (``key_id``, ``team_id``)
is a ULID (KTD4), generated via :func:`libs.ulid.generate_ulid`.

Uses ``libs.db.Database`` for every connection -- no hand-rolled psycopg
connection handling here (KTD1).
"""

import json

from typing import List, Optional

import psycopg
from psycopg.rows import dict_row

from libs.db import Database
from libs.ulid import generate_ulid


class IdentityRepository(object):
    """Repository for ``identity.*`` tables: principals, principal_keys,
    organizations, organization_members, teams, team_members."""

    def __init__(self, db=None):
        # type: (Optional[Database]) -> None
        self._db = db or Database()

    # -- principals -------------------------------------------------------

    def register_principal(
        self,
        principal_id,
        principal_type,
        display_name=None,
        home_organization_id=None,
        created_by=None,
        extensions=None,
    ):
        # type: (str, str, Optional[str], Optional[str], Optional[str], Optional[dict]) -> dict
        """Register a new principal (user, agent, verifier or service);
        return the stored row.

        Raises ``ValueError`` on a duplicate ``principal_id``, mirroring
        ``AgentIndex.register_agent``'s contract, so callers can map it to a
        409 the same way.
        """
        with self._db.transaction() as conn:
            try:
                with conn.cursor(row_factory=dict_row) as cur:
                    cur.execute(
                        """
                        INSERT INTO identity.principals
                            (principal_id, principal_type, display_name,
                             home_organization_id, created_by, extensions)
                        VALUES (%s, %s, %s, %s, %s, %s::jsonb)
                        RETURNING *
                        """,
                        (
                            principal_id,
                            principal_type,
                            display_name,
                            home_organization_id,
                            created_by,
                            _dumps(extensions or {}),
                        ),
                    )
                    return cur.fetchone()
            except psycopg.errors.UniqueViolation:
                raise ValueError(
                    "principal_id already registered: %s" % principal_id
                )

    def upgrade_principal_type(self, principal_id, principal_type, created_by=None):
        # type: (str, str, Optional[str]) -> dict
        """Change an EXISTING principal's type in place (e.g. a principal
        that registered as ``"user"`` -- to set up a signing key via the
        auth endpoint -- later also becomes a first-class Agent Principal).

        Unit U5 (database architecture): before U2/U5 unified Users and
        Agents into one ``identity.principals`` table, a principal_id used
        by both a user-registration flow and an agent-registration flow was
        two independent rows in two separate in-memory dicts -- harmless.
        Since they share one table keyed by ``principal_id``, that legitimate
        pattern (see ``registry/repository.py``'s ``register_agent_principal``
        docstring) needs an explicit "upgrade" path instead of a second
        ``INSERT`` colliding on the primary key. ``created_by`` is only set
        if not already present (an upgrade never overwrites who originally
        created the principal).
        """
        with self._db.transaction() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    UPDATE identity.principals
                       SET principal_type = %s,
                           created_by = COALESCE(created_by, %s)
                     WHERE principal_id = %s
                     RETURNING *
                    """,
                    (principal_type, created_by, principal_id),
                )
                return cur.fetchone()

    def get_principal(self, principal_id):
        # type: (str) -> Optional[dict]
        """Fetch a principal row, or ``None`` if unknown."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.principals WHERE principal_id = %s",
                    (principal_id,),
                )
                return cur.fetchone()

    def find_user_principals_by_display_name(self, display_name):
        # type: (str) -> List[dict]
        """Return active user principals with an exact display-name match."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    SELECT *
                      FROM identity.principals
                     WHERE principal_type = 'user'
                       AND status = 'active'
                       AND display_name = %s
                     ORDER BY created_at
                    """,
                    (display_name,),
                )
                return list(cur.fetchall())

    def principal_exists(self, principal_id):
        # type: (str) -> bool
        """Check if a principal exists."""
        with self._db.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT 1 FROM identity.principals WHERE principal_id = %s",
                    (principal_id,),
                )
                return cur.fetchone() is not None

    def update_last_active(self, principal_id):
        # type: (str) -> None
        """Update a principal's ``last_active_at`` timestamp to now."""
        with self._db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "UPDATE identity.principals SET last_active_at = now() "
                    "WHERE principal_id = %s",
                    (principal_id,),
                )

    # -- principal keys -----------------------------------------------------
    #
    # Exactly one ACTIVE key per principal is enforced by the database itself
    # (``principal_keys_one_active``, a unique partial index on
    # ``principal_id WHERE status = 'active'`` -- migrations/0001_identity.sql).
    # ``register_key`` deliberately does NOT pre-check for an existing active
    # key before inserting: letting the unique index raise is the contract
    # (see ``tests/lib/test_identity_repository.py``), not a bug worked around
    # here. Use :meth:`rotate_key` for the revoke-then-insert flow instead.

    def register_key(self, principal_id, public_key, key_algorithm="ed25519"):
        # type: (str, str, str) -> dict
        """Register a new key for ``principal_id`` as ``active``.

        Raises whatever ``psycopg.errors.UniqueViolation`` the database
        raises if ``principal_id`` already has an active key -- callers that
        want a rotation (revoke old, insert new, atomically) should call
        :meth:`rotate_key` instead of calling this directly.
        """
        key_id = generate_ulid()
        with self._db.transaction() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    INSERT INTO identity.principal_keys
                        (key_id, principal_id, public_key, key_algorithm)
                    VALUES (%s, %s, %s, %s)
                    RETURNING *
                    """,
                    (key_id, principal_id, public_key, key_algorithm),
                )
                return cur.fetchone()

    def revoke_key(self, key_id):
        # type: (str) -> Optional[dict]
        """Revoke a key by id; return the updated row, or ``None`` if the
        key doesn't exist. Idempotent: revoking an already-revoked key just
        re-returns its (unchanged) row rather than erroring."""
        with self._db.transaction() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    UPDATE identity.principal_keys
                    SET status = 'revoked', revoked_at = now()
                    WHERE key_id = %s AND status = 'active'
                    RETURNING *
                    """,
                    (key_id,),
                )
                row = cur.fetchone()
                if row is not None:
                    return row
                cur.execute(
                    "SELECT * FROM identity.principal_keys WHERE key_id = %s",
                    (key_id,),
                )
                return cur.fetchone()

    def rotate_key(self, principal_id, new_public_key, key_algorithm="ed25519"):
        # type: (str, str, str) -> dict
        """Atomically revoke ``principal_id``'s current active key (if any)
        and register ``new_public_key`` as the new active key. Both
        statements run in one transaction so the unique-active-key index is
        never observed in a violated state and a mid-way failure leaves the
        old key active rather than leaving the principal keyless."""
        key_id = generate_ulid()
        with self._db.transaction() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    UPDATE identity.principal_keys
                    SET status = 'revoked', revoked_at = now()
                    WHERE principal_id = %s AND status = 'active'
                    """,
                    (principal_id,),
                )
                cur.execute(
                    """
                    INSERT INTO identity.principal_keys
                        (key_id, principal_id, public_key, key_algorithm)
                    VALUES (%s, %s, %s, %s)
                    RETURNING *
                    """,
                    (key_id, principal_id, new_public_key, key_algorithm),
                )
                return cur.fetchone()

    def get_active_key(self, principal_id):
        # type: (str) -> Optional[dict]
        """The principal's current active key row, or ``None``."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.principal_keys "
                    "WHERE principal_id = %s AND status = 'active'",
                    (principal_id,),
                )
                return cur.fetchone()

    def list_keys(self, principal_id):
        # type: (str) -> List[dict]
        """All key rows (active and revoked) for a principal, newest first."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.principal_keys "
                    "WHERE principal_id = %s ORDER BY created_at DESC",
                    (principal_id,),
                )
                return cur.fetchall()

    # -- organizations --------------------------------------------------------

    def create_organization(
        self,
        organization_id,
        name,
        plan="free",
        industry=None,
        website=None,
        location=None,
    ):
        # type: (str, str, str, Optional[str], Optional[str], Optional[str]) -> dict
        """Create a new organization; return the stored row.

        Raises ``ValueError`` on a duplicate ``organization_id``.
        """
        with self._db.transaction() as conn:
            try:
                with conn.cursor(row_factory=dict_row) as cur:
                    cur.execute(
                        """
                        INSERT INTO identity.organizations
                            (organization_id, name, plan, industry, website, location)
                        VALUES (%s, %s, %s, %s, %s, %s)
                        RETURNING *
                        """,
                        (organization_id, name, plan, industry, website, location),
                    )
                    return cur.fetchone()
            except psycopg.errors.UniqueViolation:
                raise ValueError(
                    "organization_id already registered: %s" % organization_id
                )

    def get_organization(self, organization_id):
        # type: (str) -> Optional[dict]
        """Fetch an organization row, or ``None`` if unknown."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.organizations WHERE organization_id = %s",
                    (organization_id,),
                )
                return cur.fetchone()

    def organization_exists(self, organization_id):
        # type: (str) -> bool
        """Check if an organization exists."""
        with self._db.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT 1 FROM identity.organizations WHERE organization_id = %s",
                    (organization_id,),
                )
                return cur.fetchone() is not None

    # -- organization members --------------------------------------------------

    def add_member(self, organization_id, principal_id, role="member"):
        # type: (str, str, str) -> dict
        """Add ``principal_id`` to ``organization_id`` with ``role``; return
        the stored membership row.

        Raises ``ValueError`` if the principal is already a member of that
        organization (the composite primary key rejects the duplicate).
        """
        with self._db.transaction() as conn:
            try:
                with conn.cursor(row_factory=dict_row) as cur:
                    cur.execute(
                        """
                        INSERT INTO identity.organization_members
                            (organization_id, principal_id, role)
                        VALUES (%s, %s, %s)
                        RETURNING *
                        """,
                        (organization_id, principal_id, role),
                    )
                    return cur.fetchone()
            except psycopg.errors.UniqueViolation:
                raise ValueError(
                    "principal %s is already a member of organization %s"
                    % (principal_id, organization_id)
                )

    def get_member(self, organization_id, principal_id):
        # type: (str, str) -> Optional[dict]
        """Fetch one membership row, or ``None``."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.organization_members "
                    "WHERE organization_id = %s AND principal_id = %s",
                    (organization_id, principal_id),
                )
                return cur.fetchone()

    def list_members(self, organization_id, role=None):
        # type: (str, Optional[str]) -> List[dict]
        """List an organization's members, optionally filtered by ``role``."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                if role is not None:
                    cur.execute(
                        "SELECT * FROM identity.organization_members "
                        "WHERE organization_id = %s AND role = %s "
                        "ORDER BY joined_at",
                        (organization_id, role),
                    )
                else:
                    cur.execute(
                        "SELECT * FROM identity.organization_members "
                        "WHERE organization_id = %s ORDER BY joined_at",
                        (organization_id,),
                    )
                return cur.fetchall()

    def organizations_for_principal(self, principal_id):
        """Return every persisted organization membership for a principal."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.organization_members "
                    "WHERE principal_id = %s ORDER BY joined_at",
                    (principal_id,),
                )
                return cur.fetchall()

    def remove_member(self, organization_id, principal_id):
        # type: (str, str) -> bool
        """Remove a principal from an organization; return whether a row
        was actually removed."""
        with self._db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "DELETE FROM identity.organization_members "
                    "WHERE organization_id = %s AND principal_id = %s",
                    (organization_id, principal_id),
                )
                return cur.rowcount > 0

    # -- teams ------------------------------------------------------------

    def create_team(self, organization_id, name, description=None):
        # type: (str, str, Optional[str]) -> dict
        """Create a new team under ``organization_id``; return the stored
        row. ``team_id`` is a freshly generated ULID (KTD4)."""
        team_id = generate_ulid()
        with self._db.transaction() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    INSERT INTO identity.teams
                        (team_id, organization_id, name, description)
                    VALUES (%s, %s, %s, %s)
                    RETURNING *
                    """,
                    (team_id, organization_id, name, description),
                )
                return cur.fetchone()

    def get_team(self, team_id):
        # type: (str) -> Optional[dict]
        """Fetch a team row, or ``None`` if unknown."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.teams WHERE team_id = %s",
                    (team_id,),
                )
                return cur.fetchone()

    def add_team_member(self, team_id, principal_id):
        # type: (str, str) -> dict
        """Add a principal to a team; return the stored row.

        Raises ``ValueError`` if the principal is already on that team.
        """
        with self._db.transaction() as conn:
            try:
                with conn.cursor(row_factory=dict_row) as cur:
                    cur.execute(
                        """
                        INSERT INTO identity.team_members (team_id, principal_id)
                        VALUES (%s, %s)
                        RETURNING *
                        """,
                        (team_id, principal_id),
                    )
                    return cur.fetchone()
            except psycopg.errors.UniqueViolation:
                raise ValueError(
                    "principal %s is already a member of team %s"
                    % (principal_id, team_id)
                )

    def list_team_members(self, team_id):
        # type: (str) -> List[dict]
        """List a team's members, oldest addition first."""
        with self._db.connection() as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    "SELECT * FROM identity.team_members "
                    "WHERE team_id = %s ORDER BY added_at",
                    (team_id,),
                )
                return cur.fetchall()


def _dumps(value):
    # type: (dict) -> str
    """JSON-encode a dict for a ``jsonb`` column parameter."""
    return json.dumps(value)
